Replace Fuel and Promises with new HttpRequest and Try
readium/r2-opds-kotlin pull request #55
Opened 2021-04-27 00:52 UTC by stevenzeck

2021-04-30 13:39 UTC, mickael-menu requested changes
Thanks for taking a stab at this! 🚀

2021-04-30 13:39 UTC, mickael-menu commented on r2-opds/src/main/java/org/readium/r2/opds/OPDS1Parser.kt
> +        suspend fun parseUrlString(url: String): Try<ParseData, Exception> {
It could be interesting to take a `client` argument to let the app provide its own implementation if necessary.

Also an additional `parseRequest()` API taking directly an `HttpRequest` would let the app customize the HTTP headers, timeouts and other settings without a custom `HttpClient`. This way we don't need to provide `parseUrlString(url: String, headers: MutableMap<String, String>)`.

```suggestion
        suspend fun parseUrlString(url: String, client: HttpClient = DefaultHttpClient()): Try<ParseData, Exception> {
        ...
        }
        
        suspend fun parseRequest(request: HttpRequest, client: HttpClient = DefaultHttpClient()) ...
```

2021-05-01 11:18 UTC, mickael-menu commented
> I wonder why you want to make HTTP requests inside a parser... Am I missing something?

That's a good point. Down the line, I'd like to offer a more high-level API which would handle:

* A version-agnostic parser (OPDS 1 or OPDS 2)
* Transparent implementation of Authentication for OPDS
* (Maybe) Something to alleviate the issues mentioned here https://github.com/readium/mobile/discussions/20

Some of these will need control over the HTTP requests.

But for this PR, I think the goal is mostly to keep feature parity with the existing implementation while deprecating Fuel and kovenant.

2021-05-01 21:04 UTC, stevenzeck commented
Yeah, this PR was about replacing Kovenant and Fuel.  I just realized that the old functions that still use Fuel can actually use the new Http service, as long as they still use Kovenant to return a Promise.  That will at least remove the need for Fuel though.

2021-05-01 21:09 UTC, stevenzeck commented on r2-opds/src/main/java/org/readium/r2/opds/OPDS1Parser.kt
> +        suspend fun parseUrlString(url: String): Try<ParseData, Exception> {
I think we can actually just have one function in that case:  Accepts a URL as a string, and accepts an HttpClient with the default being DefaultHttpClient.  And `parseRequest` sounds better than `parseUrlString`.

2021-05-05 02:38 UTC, stevenzeck commented
@mickael-menu made the suggested changes.

2021-05-07 10:35 UTC, merged